import type { CurriculumModule } from './types';

/**
 * Modules 9-11: the adept core — day-master strength, pattern classification,
 * and favorable-god selection. This is the technical machinery a folk-table
 * reader skips and a trained reader cannot. The engine now computes all
 * three: 强弱 (the four-factor method below), 格局 (the eight regular
 * patterns plus 建禄/羊刃/从格/专旺/化气格), and 用神 (all five classical
 * methods, run as independent lenses with module 11's own decision order).
 * These three modules still teach the METHOD by hand, worked on real
 * pillars, because the tradition's judgment calls (从格 thresholds, which
 * of the five 用神 methods to trust when they disagree) are worth
 * understanding, not just reading off a screen — the engine shows its
 * work precisely so that understanding stays checkable. Some corners
 * remain outside the engine's authority and are marked honestly where
 * they appear (十二长生's yin-reversal dispute stays a teaching note; the
 * app itself computes the table).
 */
export const STRENGTH_AND_PATTERN: CurriculumModule[] = [
  {
    id: 9,
    slug: 'qiangruo',
    title: '强弱',
    pinyin: 'qiáng ruò',
    subtitle: 'day-master strength — the first judgment call',
    intro: [
      'Every method past this point depends on one question: is the day master strong or weak? Not morally — structurally. A "strong" day master has enough support (its own element, or what generates it) to withstand being drained, controlled, or spent. A "weak" one does not. Everything downstream — which 十神 helps, which pattern the chart forms, which god is favorable — flips depending on the answer. Get 强弱 wrong and every later step reads backwards.',
      'The tradition never scores this with a single number, and neither will this module pretend to. What follows is the four-factor method (得令, 得地, 得势, 通根) used to build a qualitative judgment, worked on real pillars so the process is concrete rather than mystical.',
    ],
    sections: [
      {
        heading: '得令 — commanding the season',
        chinese: '得令',
        pinyin: 'dé lìng',
        paragraphs: [
          'The single heaviest factor. 得令 asks: does the month branch\'s season favor the day master\'s element? A 甲 (yang wood) day master born in 寅卯辰 (spring) is 得令 — the season itself is wood\'s home. A 甲 born in 申酉戌 (autumn, metal\'s season, which controls wood) is not.',
          'The classical seasonal-strength doctrine names five states for a phase against the month: 旺 wàng (flourishing, its own season), 相 xiàng (supported, generated by the season), 休 xiū (resting, generates the season), 囚 qiú (confined, restrains the season), 死 sǐ (dormant, restrained by the season). 得令 means 旺 or 相; anything else is 失令 shī lìng, "losing the season."',
        ],
        table: {
          head: ['day master phase', '旺 season (得令) / 死·囚 season (失令, hardest)'],
          rows: [
            ['木 wood', '寅卯辰 spring / 申酉戌 autumn (metal controls wood)'],
            ['火 fire', '巳午未 summer / 亥子丑 winter (water controls fire)'],
            ['土 earth', '辰戌丑未 (the four turning months) / 寅卯辰 spring (wood controls earth)'],
            ['金 metal', '申酉戌 autumn / 巳午未 summer (fire controls metal)'],
            ['水 water', '亥子丑 winter / 辰戌丑未 (earth controls water)'],
          ],
        },
        terms: [
          { term: '得令', pinyin: 'dé lìng', gloss: "commanding the season — the month branch's phase supports the day master" },
          { term: '旺', pinyin: 'wàng', gloss: 'flourishing — the phase in its own season' },
          { term: '相', pinyin: 'xiàng', gloss: 'supported — the phase generated by the season' },
        ],
      },
      {
        heading: '得地 — rooted in the earth',
        chinese: '得地 · 通根',
        pinyin: 'dé dì · tōng gēn',
        paragraphs: [
          '得地 asks whether the day master finds support in the BRANCHES — not just the month, but any of the four. This is mostly a question of 通根 tōng gēn, "rooting through": does the day stem\'s element appear as a hidden stem (藏干, module 4) inside any branch of the chart? A 甲 (yang wood) day master with a 寅 branch anywhere in the chart is rooted — 寅 hides 甲 as its 主气. A 甲 with a 卯 branch is also rooted (卯 hides 乙, wood\'s yin register, a weaker but real root).',
          'Roots are not equal. A 主气 root (the branch\'s presiding hidden stem, from module 4) is a strong root; a 中气 or 余气 root is a weaker one. A day master with multiple roots across several branches is far harder to uproot than one standing on a single 余气 trace.',
        ],
        terms: [
          { term: '通根', pinyin: 'tōng gēn', gloss: "rooting through — the day master's element appears as a hidden stem in a branch" },
          { term: '得地', pinyin: 'dé dì', gloss: 'gaining ground — support found in the branches generally' },
        ],
      },
      {
        heading: '得势 — support from the stems',
        chinese: '得势',
        pinyin: 'dé shì',
        paragraphs: [
          '得势 asks about the visible STEMS: do the other three stems (year, month, hour) generate or share the day master\'s element? A 甲 day master with a 壬 or 癸 stem elsewhere (water generates wood) or another 甲/乙 stem (a peer or rival) gains 得势. This is the weakest of the three factors alone, but stacks with 得令 and 得地 — a day master strong in season, root, AND stem support is about as strong as a chart gets.',
        ],
      },
      {
        heading: 'putting it together — a worked judgment',
        paragraphs: [
          'Take the app\'s worked example from module 6: 己卯 · 丙子 · 戊午 · 戊午 (born 2000-01-01, noon, Beijing). Day master 戊 (yang earth). Month branch 子 (water\'s own season) — the day master itself controls the season (土克水, earth controls water), which spends the day master\'s energy rather than feeding it: this is 囚 qiú, "confined." Either way the season sits opposite the day master, this reads as 失令: the day master does NOT command the season.',
          'Check 得地: does 戊 (earth) root anywhere? The day branch 午 hides 丁己 (主气 丁, 余气 己) — 己 is earth\'s yin register, a real but secondary root. The hour branch is also 午 — the same secondary root, doubled. Some root, but not the strongest kind.',
          'Check 得势: the other stems are 己 (year, earth — a peer, direct support) and 丙 (month, fire — generates earth, support). Two supporting stems.',
          'Verdict: 失令 (lost the season) but real support from stems and a doubled secondary root — this reads as a day master on the WEAK side of the line, but not collapsed. The tradition calls this a 身弱 (body weak) chart that still has resource — exactly the kind of case where the four factors have to be weighed together, not read off one alone.',
        ],
      },
      {
        heading: 'the twelve stages of growth — 十二长生',
        chinese: '十二长生',
        pinyin: 'shí èr cháng shēng',
        paragraphs: [
          'A finer-grained lens the tradition lays over every stem-branch pairing: twelve stages of a life cycle, from birth to burial, mapped onto the twelve branches for each of the ten stems. 长生 (birth), 沐浴 (bathing), 冠带 (capping), 临官 (office), 帝旺 (imperial peak — the strongest stage, same idea as 旺 above but stem-specific), 衰 (decline), 病 (illness), 死 (death), 墓 (tomb/vault — the same 库 seats from module 8\'s 三合 groups), 绝 (severance), 胎 (conception), 养 (nurture).',
          'Each stem has its own cycle direction (yang stems run forward through the twelve branches from their 长生 seat; yin stems run backward — a doctrine detail with real disagreement between schools on whether yin stems truly reverse). The engine computes this table exactly — pinned against the same lunar_python oracle every other doctrine table is checked against, not re-derived from a formula — and uses it as a finer supplement to 得地 above: a day master sitting on its own 帝旺/临官/长生 seat scores as real strength even without a literal 藏干 root match; its 死/绝/病 seat scores the opposite.',
          'Honest note: 十二长生 is real, widely taught doctrine — and also one of the more school-divided corners of the system (the yin-reversal question above is unresolved between traditions, though it is exactly what the oracle pinning verifies: the reversal is not a guess here, it is checked). The app computes the table for every stem-branch pairing; this module teaches what the stages mean so a computed 帝旺 or 死 seat is legible, not just a label.',
        ],
        terms: [
          { term: '帝旺', pinyin: 'dì wàng', gloss: "imperial peak — a stem's strongest of the twelve growth stages" },
          { term: '长生', pinyin: 'cháng shēng', gloss: "birth — the first of the twelve growth stages" },
          { term: '墓', pinyin: 'mù', gloss: 'tomb/vault stage — the same seats as the 三合 storehouse branches' },
        ],
      },
    ],
  },
  {
    id: 10,
    slug: 'geju',
    title: '格局',
    pinyin: 'gé jú',
    subtitle: 'pattern — classifying the whole chart',
    intro: [
      'Once you can judge strength, the next question is shape: what KIND of chart is this? 格局 gé jú, "pattern" or "structure," is the tradition\'s classification system — a chart is read as belonging to one dominant pattern, usually named for whichever 十神 governs the month branch (the chart\'s single most powerful seat, per module 9\'s 得令).',
      'Patterns matter because they set the chart\'s agenda before you ever pick a favorable god (module 11): a 正官格 chart wants its officer protected and fed; a 食神格 chart wants its output unblocked; a 从格 chart (below) inverts the whole strength question. Classify first, then choose.',
    ],
    sections: [
      {
        heading: 'the eight regular patterns — 八格',
        chinese: '八格',
        pinyin: 'bā gé',
        paragraphs: [
          'The classical eight patterns are named directly for the 十神 that the month branch\'s 主气 (module 4\'s "presiding stem") represents to the day master. Two of the ten 十神 are excluded by convention (比肩 and 劫财 — "peer" patterns are handled separately, below, as 建禄/羊刃), leaving eight:',
          'Each pattern carries its own agenda, in brief: 正官格 wants the officer protected from 伤官\'s attack and fed by 财; 七杀格 wants the pressure controlled (by 食神 or 印) rather than left to run wild; 正财/偏财格 want the wealth guarded from 比劫\'s theft; 正印/偏印格 want the resource neither drowned by excess 财 nor starved; 食神格 wants its output unblocked by 枭神 (module 7\'s owl pattern); 伤官格 is the most contested pattern in the whole system — brilliant but rule-breaking, and schools disagree sharply on whether it wants 官 controlled, avoided, or fed by 财 as a release valve.',
        ],
        table: {
          head: ['pattern name', 'the month\'s presiding 十神'],
          rows: [
            ['正官格', '正官 — the discipline, crossed register'],
            ['七杀格', '七杀 — the pressure, same register (also called 偏官格)'],
            ['正财格', '正财 — the wealth, crossed register'],
            ['偏财格', '偏财 — the wealth, same register'],
            ['正印格', '正印 — the resource, crossed register'],
            ['偏印格', '偏印 — the resource, same register'],
            ['食神格', '食神 — the output, same register'],
            ['伤官格', '伤官 — the talent, crossed register'],
          ],
        },
      },
      {
        heading: 'when the month is a peer — 建禄 and 羊刃',
        chinese: '建禄格 · 羊刃格',
        pinyin: 'jiàn lù gé · yáng rèn gé',
        paragraphs: [
          'When the month branch\'s presiding stem IS the day master\'s own element (a 比肩 or 劫财 relation), the eight-pattern table above does not apply — the tradition names two special patterns instead. 建禄格 jiàn lù gé ("establishing the salary") is the yang-polarity case: the day master sits on its own 禄 (module 12\'s "salary" star) in the month. 羊刃格 yáng rèn gé ("sheep blade") is the yin-adjacent case, named for a stem sitting on its own blade-branch (also module 12) — read as raw, cutting strength that needs the 七杀 or 官 to discipline it, the way a blade needs a sheath.',
          'Both patterns describe a day master already at its structural peak from the month alone — read them as "extremely strong by 得令" cases, and go straight to asking what controls or channels that strength (module 11\'s 扶抑 logic, in its "抑" direction).',
        ],
        terms: [
          { term: '建禄格', pinyin: 'jiàn lù gé', gloss: 'establishing-the-salary pattern — the day master sits on its own 禄 in the month' },
          { term: '羊刃格', pinyin: 'yáng rèn gé', gloss: 'sheep-blade pattern — the day master sits on its own blade-branch in the month; raw, cutting strength' },
        ],
      },
      {
        heading: 'when the chart refuses balance — 从格',
        chinese: '从格',
        pinyin: 'cóng gé',
        paragraphs: [
          'Every pattern above assumes the day master is a real player worth balancing FOR. 从格 "following patterns" are the exception: charts so lopsided that the day master gives up the fight and "follows" whatever dominates instead. These are read only after strength (module 9) comes back extreme in one direction, with no real root or support to counter it — a 从格 misread as a normal chart inverts every subsequent judgment.',
          '从旺格 cóng wàng gé ("following abundance") — the day master is extremely strong (heavy 得令+得地+得势, no controlling 官杀 present) and simply leans into its own strength rather than seeking balance. 从弱格 splits into direction-specific names by what the chart follows: 从儿格 cóng ér gé ("following the child") when the chart is dominated by what the day master generates (食伤); 从财格 cóng cái gé when dominated by wealth (财); 从杀格 cóng shā gé when dominated by the pressure (七杀/官). The common thread: the day master has essentially no root and no support, so instead of resisting the dominant force it "follows" it — and the favorable god (module 11) flips to STRENGTHEN the dominant force rather than rescue the day master.',
          'Honest caution: 从格 is real doctrine but the single most argued-over judgment call in the whole system — different schools set different thresholds for "no root at all," and a marginal case read as 从格 by one reader is a normal weak chart to another. Treat a 从格 call as a hypothesis to hold loosely, not a settled fact — this is exactly the kind of judgment the app deliberately does not automate.',
        ],
        terms: [
          { term: '从旺格', pinyin: 'cóng wàng gé', gloss: 'following-abundance — an extremely strong day master leans into its own strength' },
          { term: '从儿格', pinyin: 'cóng ér gé', gloss: 'following-the-child — a rootless day master follows what it generates (食伤)' },
          { term: '从财格', pinyin: 'cóng cái gé', gloss: 'following-wealth — a rootless day master follows the wealth element' },
          { term: '从杀格', pinyin: 'cóng shā gé', gloss: 'following-the-pressure — a rootless day master follows 七杀/官' },
        ],
      },
      {
        heading: 'the rarest patterns — 化气格',
        chinese: '化气格',
        pinyin: 'huà qì gé',
        paragraphs: [
          'A pattern condition tied directly to module 3\'s 五合 (stem combinations): if the day stem itself combines with an adjacent stem (甲己, 乙庚, 丙辛, 丁壬, 戊癸) AND the resulting transformed element is strongly supported by the month and the rest of the chart, some schools read the day master as having transformed entirely into that new element — 化气格, "transformed-qi pattern." This is the rarest and most disputed pattern classification; many readers require near-perfect support (the transformed element commanding the season, no competing element present) before accepting it.',
          'Honest note: the engine computes this candidacy exactly — it checks whether the day stem combines with an adjacent stem (module 3\'s 五合 table) and how much of the rest of the chart\'s branches support the transformed element, then surfaces it as a flagged CANDIDATE with its evidence shown, never a silent override of the regular pattern above. This is deliberate: 化气格 is real doctrine but the single most disputed classification in the system, so the app names the evidence and leaves the acceptance threshold — "near-perfect support," and how near is near enough — to you.',
        ],
      },
      {
        heading: 'classifying the worked example',
        paragraphs: [
          'Back to 己卯 · 丙子 · 戊午 · 戊午. Day master 戊 (earth), month branch 子 (water, 主气 癸). 癸 to 戊: opposite polarity, and the day master controls the month\'s presiding stem (土克水, earth controls water) — check via module 7\'s table: 戊 vs 癸, opposite polarity, "I control it" position → 正财. So the month\'s presiding god is 正财 — this chart classifies as 正财格, not the resource pattern the strength judgment might suggest at a glance.',
          'A 正财格 wants its wealth guarded from 比劫\'s theft and fed by 食伤\'s output. Paired with module 9\'s finding (this day master is 身弱 but not collapsed), pattern and strength POINT IN DIFFERENT DIRECTIONS here: 正财格\'s own agenda wants the wealth protected and channeled, while 扶抑\'s 身弱 verdict wants the day master supported first. Module 11 will show exactly this kind of disagreement is not a bug in the method — it is the honest finding a real chart can produce, and both lenses stay visible rather than one silently overriding the other.',
        ],
      },
    ],
  },
  {
    id: 11,
    slug: 'yongshen',
    title: '用神',
    pinyin: 'yòng shén',
    subtitle: 'the favorable god — five ways to choose it',
    intro: [
      '用神 yòng shén, "the useful god," is the single element (expressed as a 十神) the chart most needs — the direction a life bends toward ease when it shows up in a 大运 or 流年, and toward strain when it is missing or attacked. Selecting it correctly is the payoff of modules 9 and 10: strength tells you which direction the chart leans; pattern tells you what shape it has taken; 用神 tells you what to actually watch for in the moving decades and years (module 14).',
      'The tradition does not have one method — it has (at least) five, and serious readers use the one that fits the chart in front of them, sometimes combining two. This module teaches all five as a decision procedure, not a single formula — and the engine now runs all five as independent, inspectable lenses, applying this module\'s own decision order to surface a recommendation while showing every lens\'s full reasoning, never a bare answer.',
    ],
    sections: [
      {
        heading: '扶抑 — supporting or restraining',
        chinese: '扶抑',
        pinyin: 'fú yì',
        paragraphs: [
          "The default method, and the one module 9's strength judgment feeds directly. If the day master is weak (身弱), the favorable direction is 扶 fú — support: 印 (resource, generates the day master) or 比劫 (peer, shares the day master's element). If the day master is strong (身强), the favorable direction is 抑 yì — restraint: 官杀 (discipline/pressure, controls the day master), 食伤 (output, drains the day master), or 财 (wealth, the day master controls it and so is drained by controlling it).",
          "Applied to the worked chart: 身弱 (module 9's verdict) → the favorable direction is 扶, support: 印 (癸/子 water) or 比劫. Notice this does NOT match the chart's own 正财格 (module 10) — the pattern's own agenda (protect and channel the wealth) and the strength method's prescription (support the day master) point different ways. This is the more common case than the two lenses agreeing, and module 11's own discipline is to show both, not silently prefer one.",
        ],
      },
      {
        heading: '调候 — climate as the tiebreaker',
        chinese: '调候',
        pinyin: 'tiáo hòu',
        paragraphs: [
          "Module 8 introduced 调候 as raw climate: winter charts want fire, summer charts want water. As a 用神 method, it is a specific claim — that for charts born deep in an extreme season (especially 子/丑 winter months or 午/未 summer months), the chart's most urgent need is temperature regulation, and this can OUTRANK the 扶抑 strength calculus. A winter-born 身强 chart that would classically want 抑 (restraint) may still need fire first, because a strong-but-freezing chart cannot function until it is warmed — 调候 supplies what 扶抑 alone would miss.",
          'Applied to the worked chart: month branch 子 is deep winter — by 调候 alone, this chart wants 丙 (fire) urgently. The month stem IS 丙. This is not a coincidence worth over-reading (丙 was already required by the 五虎遁 rule from a 己 year, module 6) — but it does mean the chart\'s 调候 need happens to already be met by a stem present in the chart itself, which a trained reader would flag as a small strength in the chart\'s own construction, independent of the 扶抑 finding. Because this chart\'s strength does not read extreme, 调候 stays a secondary confirmation here rather than outranking 扶抑 (module 11\'s own decision order: 调候 jumps the queue only when strength is already lopsided).',
        ],
      },
      {
        heading: '病药 — the illness and its medicine',
        chinese: '病药',
        pinyin: 'bìng yào',
        paragraphs: [
          'A more surgical method: identify the chart\'s single most damaging element or structure (its "illness," 病) and let the 用神 be whatever directly cures it (its "medicine," 药). Where 扶抑 asks a general strength question, 病药 asks a specific diagnostic one — is there one 十神 so excessive or so damaging that fixing IT is the chart\'s actual priority, ahead of the general strength balance?',
          'Classic 病药 cases: an over-strong 枭神 (module 7) smothering 食神 — the illness is the owl, the medicine is 财破印 (a 财 stem controlling the excess resource). An unchecked 七杀 attacking a weak day master — the illness is the unchecked pressure, the medicine is 食神 or 印 to control or absorb it. 病药 is most useful exactly when 扶抑\'s general prescription and the chart\'s worst structural problem point in different directions — then the illness/medicine read takes priority.',
        ],
      },
      {
        heading: '通关 — bridging a stuck conflict',
        chinese: '通关',
        pinyin: 'tōng guān',
        paragraphs: [
          'When two elements in a chart sit in direct 克 (module 2\'s restraining cycle) with roughly equal strength — a stalemate, not a clear winner — the favorable god can be the element that BRIDGES them: the one the first generates and that in turn generates (or otherwise appeases) the second. This is 通关 tōng guān, "connecting the pass." A chart with strong 金 directly opposing strong 木 (metal felling wood) with neither side yielding might favor 水 — water the metal generates, which in turn nourishes the wood — turning a standoff into a flow.',
          '通关 is the method to reach for when a chart reads as "stuck" rather than simply strong or weak — two roughly matched forces locked against each other, where more of either side just escalates the conflict instead of resolving it.',
        ],
      },
      {
        heading: '专旺 — when overwhelming force is nourished, not fought',
        chinese: '专旺',
        pinyin: 'zhuān wàng',
        paragraphs: [
          'The formal name for what module 10\'s 从旺格 already described from the pattern side: when one element so thoroughly dominates a chart that there is no reasonable point of resistance, the favorable god STRENGTHENS the dominant element rather than opposing it — 比劫 and 印 (what shares and what generates the dominant force), never 官杀/财/食伤 (anything that would fight it). 专旺 is 从旺格\'s 用神 method: name the pattern with module 10, then apply 专旺\'s "join it, don\'t fight it" logic here.',
        ],
      },
      {
        heading: 'choosing among the five — a decision order',
        paragraphs: [
          'In practice: start with 扶抑 (module 9\'s strength verdict) as the default frame. Check 调候 — if the chart is born in a climate extreme, does temperature outrank the 扶抑 call? Check 病药 — is there one specific illness so damaging it should take priority over the general balance? Check whether the chart is genuinely 从格/专旺 territory (module 10) before applying normal 扶抑 logic at all — a true 从格 case inverts everything. Reach for 通关 only when two forces read as genuinely locked, not merely present.',
          'These are not five competing final answers — they are five lenses, and a mature reading often finds two or three of them agreeing. The worked example above is the more instructive case: 扶抑 wants 印/比劫 (support the day master) while the chart\'s own 正财格 pattern wants its wealth protected and channeled — two real, computed findings that point different ways. That disagreement is itself the honest finding — note it, and hold the conclusion loosely, exactly as this whole project holds every conclusion: computed structure, human reading, never a verdict.',
        ],
      },
    ],
  },
];
