#!/usr/bin/env python3
"""Generate app/lib/cities.ts from GeoNames cities15000 (pop >= 100k).

Provenance: https://download.geonames.org/export/dump/cities15000.zip
(cc-by-4.0, geonames.org). Regenerate:
    curl -sO https://download.geonames.org/export/dump/cities15000.zip
    unzip -o cities15000.zip && curl -sO https://download.geonames.org/export/dump/countryInfo.txt
    python3 tools/gen_cities.py cities15000.txt countryInfo.txt > app/lib/cities.ts

Output: a single packed string (name|CC[|admin1]|lon|tzId;...) sorted by
population desc, plus a CC -> country-name map. ~250 KB bundled, parsed once
at module load; keeps birth-place lookup fully client-side.
"""
import sys
import unicodedata


def ascii_name(name: str, asciiname: str) -> str:
    # Prefer the plain name when it is already ASCII-typable; else the asciiname.
    if all(ord(c) < 128 for c in name) and "|" not in name and ";" not in name:
        return name
    return asciiname


def main(cities_path: str, country_path: str) -> None:
    countries = {}
    with open(country_path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 5:
                countries[parts[0]] = parts[4]

    rows = []
    with open(cities_path, encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) < 18:
                continue
            try:
                pop = int(p[14])
                lon = float(p[5])
            except ValueError:
                continue
            if pop < 100000:
                continue
            name = ascii_name(p[1], p[2])
            cc, admin1, tz = p[8], p[10], p[17]
            if not tz or not name:
                continue
            # hard-sanitize delimiters; keep positions fixed (admin may be empty)
            name = name.replace(";", ",").replace("|", ",")
            # US/CA/AU/etc. state codes help disambiguate same-name cities.
            admin = admin1 if len(admin1) == 2 and admin1.isalpha() and admin1.isupper() else ""
            rows.append((pop, name, cc, admin, round(lon, 2), tz))

    rows.sort(key=lambda r: -r[0])

    used_cc = sorted({r[2] for r in rows})
    packed = ";".join(
        f"{name}|{cc}|{admin}|{lon}|{tz}"
        for _, name, cc, admin, lon, tz in rows
    )
    cmap = ", ".join(f'{cc}:"{countries[cc]}"' for cc in used_cc if cc in countries)

    print("// GENERATED by tools/gen_cities.py from GeoNames cities15000 + countryInfo")
    print("// (cc-by-4.0, https://geonames.org) — pop >= 100k, sorted by population desc.")
    print("// Do not edit by hand; regenerate instead.")
    print()
    print("export interface CityEntry {")
    print("  name: string;")
    print("  cc: string;")
    print("  admin: string;")
    print("  lon: number;")
    print("  tz: string;")
    print("}")
    print()
    print('export const COUNTRY_NAMES: Record<string, string> = {' + cmap + "};")
    print()
    print("const PACKED =")
    # chunk the string literal to keep lines manageable
    for i in range(0, len(packed), 4000):
        chunk = packed[i : i + 4000]
        esc = chunk.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
        print("  `" + esc + "` +")
    print('  "";')
    print()
    print("export const CITIES: CityEntry[] = PACKED.split(\";\").map((s) => {")
    print("  const [name, cc, admin, lon, tz] = s.split(\"|\");")
    print("  return { name, cc, admin: admin ?? \"\", lon: Number(lon), tz };")
    print("});")
    print()
    print(f"// {len(rows)} cities, {len(used_cc)} countries")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
